#!/usr/bin/env bash
# Writes THIRD-PARTY-NOTICES.txt, and the copies of it and of LICENSE that the app
# carries as resources (Sources/octetly/Resources/THIRD-PARTY-NOTICES.txt and
# Sources/octetly/Resources/LICENSE.txt). The app shows them from the
# "Third-Party Licenses…" menu item and from `octetly --license`.
#
#   scripts/generate-third-party-notices.sh           # rewrite the files
#   scripts/generate-third-party-notices.sh --check   # exit 1 if they are stale
#
# Octetly has no package dependencies: it is built from the Swift standard
# library and Apple's frameworks, which are part of macOS and are not shipped in
# the app. So the notices say that, and this script's job is to make sure it is
# still true. The moment Package.swift gains a `.package(...)` dependency this
# script stops with an error instead of writing a notice that has become false;
# it then has to be extended to read the pins in Package.resolved and the
# LICENSE files under .build/checkouts/ (which needs a macOS machine to resolve).
#
# The copies under Sources/ exist because SwiftPM can only bundle files that are
# inside the target's directory. Tests/OctetlyTests/LicenseTests.swift checks
# that they match the files at the top of the repository, and the release
# workflow runs this script with --check, so a forgotten regeneration fails
# before a merge rather than shipping.
set -euo pipefail

cd "$(dirname "$0")/.."

CHECK=0
case "${1:-}" in
  "") ;;
  --check) CHECK=1 ;;
  *)
    echo "Usage: scripts/generate-third-party-notices.sh [--check]" >&2
    exit 1
    ;;
esac

# SwiftPM's own reading of the manifest is the authority, and it is what runs in
# CI (macOS). Without a Swift toolchain (a Linux checkout) the manifest text is
# searched instead, with all whitespace removed so that a call split across
# lines, `.package\n(`, is still found.
if command -v swift >/dev/null 2>&1; then
  DEPENDENCY_COUNT=$(swift package dump-package \
    | python3 -c 'import json, sys; print(len(json.load(sys.stdin).get("dependencies", [])))')
elif tr -d '[:space:]' < Package.swift | grep -q '\.package('; then
  DEPENDENCY_COUNT=1
else
  DEPENDENCY_COUNT=0
fi
if [ "$DEPENDENCY_COUNT" -ne 0 ]; then
  echo "Error: Package.swift declares a package dependency." >&2
  echo "  This script only knows how to describe a package with none. Extend it to" >&2
  echo "  list the pins in Package.resolved with the LICENSE files from" >&2
  echo "  .build/checkouts/ before regenerating the notices." >&2
  exit 1
fi
if [ -f Package.resolved ] && grep -q '"identity"' Package.resolved; then
  echo "Error: Package.resolved has pins, but Package.swift declares no dependency." >&2
  echo "  Resolve the package again (swift package resolve) and rerun." >&2
  exit 1
fi

RESOURCES="Sources/octetly/Resources"
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

RULE_HASH=$(printf '#%.0s' $(seq 1 80))
RULE_EQ=$(printf '=%.0s' $(seq 1 80))

cat > "$WORK/THIRD-PARTY-NOTICES.txt" <<NOTICES
THIRD-PARTY NOTICES

This file lists the third-party libraries and data bundled with Octetly. Each
entry gives the license or source, what it applies to, and the license text as
shipped by the package where there is one. Generated by
scripts/generate-third-party-notices.sh; do not edit by hand.

${RULE_HASH}
# Swift packages (compiled into the binary)
${RULE_HASH}

${RULE_EQ}
None.

Octetly does not bundle any third-party library. It is built from the Swift
standard library and Apple's system frameworks (SwiftUI, AppKit, Foundation and
others), which are part of macOS and are not shipped with the app.

${RULE_HASH}
# Bundled data
${RULE_HASH}

${RULE_EQ}
Source: IEEE Registration Authority

Used by:
  oui.csv (vendor names for MAC address prefixes)

Sources/octetly/Resources/oui.csv is compiled by scripts/update-oui.py from the
public MA-L, MA-M and MA-S assignment listings published by the IEEE
Registration Authority:

  https://standards-oui.ieee.org/oui/oui.csv
  https://standards-oui.ieee.org/oui28/mam.csv
  https://standards-oui.ieee.org/oui36/oui36.csv
NOTICES

cp LICENSE "$WORK/LICENSE.txt"

if [ "$CHECK" -eq 1 ]; then
  stale=0
  for pair in \
    "THIRD-PARTY-NOTICES.txt:THIRD-PARTY-NOTICES.txt" \
    "THIRD-PARTY-NOTICES.txt:$RESOURCES/THIRD-PARTY-NOTICES.txt" \
    "LICENSE.txt:$RESOURCES/LICENSE.txt"; do
    generated="$WORK/${pair%%:*}"
    committed="${pair#*:}"
    if [ ! -f "$committed" ] || ! cmp -s "$generated" "$committed"; then
      echo "Stale: $committed" >&2
      stale=1
    fi
  done
  if [ "$stale" -ne 0 ]; then
    echo "Run scripts/generate-third-party-notices.sh and commit the result." >&2
    exit 1
  fi
  echo "Third-party notices are up to date."
  exit 0
fi

# Written beside their destinations and moved into place, so that a run that
# fails halfway leaves the old files rather than half-written ones.
cp "$WORK/THIRD-PARTY-NOTICES.txt" THIRD-PARTY-NOTICES.txt.tmp
mv THIRD-PARTY-NOTICES.txt.tmp THIRD-PARTY-NOTICES.txt
cp "$WORK/THIRD-PARTY-NOTICES.txt" "$RESOURCES/THIRD-PARTY-NOTICES.txt.tmp"
mv "$RESOURCES/THIRD-PARTY-NOTICES.txt.tmp" "$RESOURCES/THIRD-PARTY-NOTICES.txt"
cp "$WORK/LICENSE.txt" "$RESOURCES/LICENSE.txt.tmp"
mv "$RESOURCES/LICENSE.txt.tmp" "$RESOURCES/LICENSE.txt"
echo "Wrote THIRD-PARTY-NOTICES.txt, $RESOURCES/THIRD-PARTY-NOTICES.txt and $RESOURCES/LICENSE.txt"
